### ISSUE TITLE
Coverage measurement by Codecov

### ISSUE THREAD

**Issue by gustawdaniel** [Canop/terminal-clipboard#10]
To measure code coverage we can append to test workflow code:

```yaml
      - name: Run tests
        run: cargo test --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      - name: Install grcov
        run: cargo install grcov

      - name: Generate coverage report
        run: |
          zip -0 ccov.zip `find . \( -name "*.gc*" \) -print`
          grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
          file: lcov.info
```

but @Canop have to add secret `CODECOV_TOKEN` from Codecov
